# Site
title:              "Red1 Design"
locale:             en_US
url:                https://red1design.github.io

# Jekyll
permalink:          date
markdown:           kramdown
highlighter:        rouge
kramdown:
  hard_wrap: true
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false